const SUPABASE_URL='https://mtpsxtkqltjypmisbguh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_gBXKSl2nZc4BzAXZXwSFFg_R2owgWhk';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; let historyData=[],currentSummary='model',bootFinished=false;
const normalizeText=v=>String(v??'').trim().replace(/\s+/g,' ').toLowerCase();
const today=()=>{const d=new Date();const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const fmtDate=v=>v?new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v+'T00:00:00')):'-';
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function setLoading(pct,status){$('#loadingProgress').style.width=`${Math.max(0,Math.min(100,pct))}%`;$('#loadingStatus').textContent=status}
async function boot(){const started=Date.now(),MAX=45000,DB_WAIT=12000;setLoading(4,'Menyiapkan aplikasi...');const timer=setInterval(()=>{const elapsed=Date.now()-started;const pct=Math.min(94,(elapsed/MAX)*94);setLoading(pct,elapsed<DB_WAIT?'Menghubungkan database...':'Menyiapkan tampilan...')},200);let result;try{result=await Promise.race([db.from('service_history').select('id',{count:'exact',head:true}),new Promise(r=>setTimeout(()=>r({timeout:true}),DB_WAIT))]);if(result?.error)setLoading(94,'Database belum dapat diakses. Membuka aplikasi...');else if(result?.timeout)setLoading(94,'Koneksi lambat. Membuka aplikasi...');else setLoading(100,'Terhubung ke Supabase')}catch(e){console.warn(e);setLoading(94,'Koneksi tidak tersedia. Membuka aplikasi...')}finally{clearInterval(timer);const elapsed=Date.now()-started;const reveal=()=>{if(bootFinished)return;bootFinished=true;$('#loadingScreen').classList.add('hidden');$('#app').classList.remove('hidden');refreshAll()};setTimeout(reveal,Math.max(0,Math.min(700,MAX-elapsed)));setTimeout(reveal,MAX-elapsed)}}
async function refreshAll(){await loadHistory();updateConnection();renderSummary(currentSummary);renderParts()}
async function loadHistory(){const {data,error}=await db.from('service_history_view').select('*').is('archived_at',null).order('service_date',{ascending:false}).order('created_at',{ascending:false}).order('id',{ascending:false});if(error){console.error(error);historyData=[];showConnectionError(error.message);return}historyData=data||[];renderHistory();updateStats();hideConnectionError()}
function showConnectionError(msg){setConn('error','Koneksi/data belum tersedia');const el=$('#historyEmpty');el.classList.remove('hidden');el.textContent=msg||'Koneksi database gagal.'}
function hideConnectionError(){ }
function setConn(type,text){const pill=$('#connectionPill');pill.className='connection-pill '+type;pill.innerHTML=`<span class="dot"></span><span>${escapeHtml(text)}</span>`}
async function updateConnection(){const {error}=await db.from('service_history').select('id',{head:true});setConn(error?'error':'online',error?'Periksa Supabase':'Terhubung')}
function updateStats(){const total=historyData.length;$('#totalRecords').textContent=total;$('#activeRecords').textContent=historyData.filter(x=>!x.archived_at).length;$('#totalPcs').textContent=historyData.reduce((s,x)=>s+(Number(x.jumlah_pcs)||0),0)}
function renderHistory(){const q=normalizeText($('#historySearch').value);const rows=historyData.filter(x=>!q||[x.phone_model,x.damage,x.action_part,x.notes].some(v=>normalizeText(v).includes(q)));const list=$('#historyList');list.innerHTML=rows.map(x=>`<article class="history-item"><button class="history-edit" data-edit="${x.id}" aria-label="Edit">✎</button><div class="history-date">${fmtDate(x.service_date)}</div><div class="history-model">${escapeHtml(x.phone_model)}</div><div class="history-line">${escapeHtml(x.damage)}</div>${x.action_part?`<div class="history-part">🔧 ${escapeHtml(x.action_part)} • <b>${Number(x.jumlah_pcs)||0} pcs</b></div>`:'<div class="history-part">Diagnosis tanpa part</div>'}${x.notes?`<div class="history-line">${escapeHtml(x.notes)}</div>`:''}</article>`).join('');$('#historyEmpty').classList.toggle('hidden',rows.length>0);$$('[data-edit]').forEach(b=>b.addEventListener('click',()=>openEdit(b.dataset.edit)))}
function renderSummary(kind){currentSummary=kind;$$('.summary-tab').forEach(b=>b.classList.toggle('active',b.dataset.summary===kind));const field={model:'phone_model',damage:'damage',part:'action_part'}[kind];const m=new Map();historyData.forEach(x=>{const val=x[field];if(!val)return;const key=normalizeText(val);if(!key)return;const cur=m.get(key)||{name:val,cases:0,pcs:0};cur.cases++;cur.pcs+=Number(x.jumlah_pcs)||0;m.set(key,cur)});const rows=[...m.values()].sort((a,b)=>b.cases-a.cases||b.pcs-a.pcs).slice(0,100);$('#summaryList').innerHTML=rows.length?rows.map(r=>`<div class="summary-row"><div><div class="summary-main">${escapeHtml(r.name)}</div><div class="summary-sub">${r.cases} kasus servis</div></div><div class="summary-number">${r.pcs} pcs</div></div>`).join(''):'<div class="empty">Belum ada data untuk dianalisa.</div>'}
function renderParts(){const m=new Map();historyData.forEach(x=>{if(!x.action_part)return;const k=normalizeText(x.action_part);const cur=m.get(k)||{name:x.action_part,cases:0,pcs:0};cur.cases++;cur.pcs+=Number(x.jumlah_pcs)||0;m.set(k,cur)});const rows=[...m.values()].sort((a,b)=>b.pcs-a.pcs||b.cases-a.cases);$('#partsList').innerHTML=rows.length?rows.map(r=>`<div class="summary-row"><div><div class="summary-main">${escapeHtml(r.name)}</div><div class="summary-sub">${r.cases} kasus • semua tipe HP</div></div><div class="summary-number">${r.pcs} pcs</div></div>`).join(''):'<div class="empty">Belum ada part yang tercatat.</div>'}
function openAdd(){$('#modalTitle').textContent='Tambah Riwayat';$('#editId').value='';$('#serviceDate').value=today();$('#phoneModel').value='';$('#damage').value='';$('#actionPart').value='';$('#jumlahPcs').value='1';$('#notes').value='';$('#formError').classList.add('hidden');$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
function openEdit(id){const x=historyData.find(r=>r.id===id);if(!x)return;$('#modalTitle').textContent='Edit Riwayat';$('#editId').value=x.id;$('#serviceDate').value=x.service_date;$('#phoneModel').value=x.phone_model;$('#damage').value=x.damage;$('#actionPart').value=x.action_part||'';$('#jumlahPcs').value=Number(x.jumlah_pcs)||0;$('#notes').value=x.notes||'';$('#formError').classList.add('hidden');$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true')}
function validateForm(){const part=$('#actionPart').value.trim(),pcs=Number($('#jumlahPcs').value);if(!$('#phoneModel').value.trim())return'Tipe HP wajib diisi.';if(!$('#damage').value.trim())return'Kerusakan wajib diisi.';if(part&&(!Number.isInteger(pcs)||pcs<1))return'Jumlah part minimal 1 pcs.';if(!part&&pcs!==0)return'Jika Tindakan / Part kosong, Jumlah / PCS harus 0.';return null}
async function saveHistory(e){e.preventDefault();const err=validateForm();if(err){$('#formError').textContent=err;$('#formError').classList.remove('hidden');return}$('#formError').classList.add('hidden');const payload={service_date:$('#serviceDate').value,phone_model:$('#phoneModel').value.trim(),damage:$('#damage').value.trim(),action_part:$('#actionPart').value.trim()||null,jumlah_pcs:Number($('#jumlahPcs').value),notes:$('#notes').value.trim()||null};const id=$('#editId').value;const result=id?await db.from('service_history').update(payload).eq('id',id):await db.from('service_history').insert(payload);if(result.error){$('#formError').textContent=result.error.message;$('#formError').classList.remove('hidden');return}closeModal();await refreshAll()}
function switchTab(tab){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));[['history','historyView'],['summary','summaryView'],['parts','partsView']].forEach(([k,id])=>$('#'+id).classList.toggle('hidden',k!==tab));if(tab==='summary')renderSummary(currentSummary);if(tab==='parts')renderParts()}
$('#addBtn').addEventListener('click',openAdd);$('#heroAdd').addEventListener('click',openAdd);$('#closeModal').addEventListener('click',closeModal);$('#cancelModal').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target.dataset.close)closeModal()});$('#historyForm').addEventListener('submit',saveHistory);$('#historySearch').addEventListener('input',renderHistory);$('#refreshBtn').addEventListener('click',refreshAll);$$('.tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));$$('.summary-tab').forEach(b=>b.addEventListener('click',()=>renderSummary(b.dataset.summary)));$('#actionPart').addEventListener('input',()=>{if(!$('#actionPart').value.trim())$('#jumlahPcs').value='0';else if(Number($('#jumlahPcs').value)===0)$('#jumlahPcs').value='1'});boot();
